name: Build, Push, and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker Image
        run: docker build -t mohanapriya1808/2048-game:latest .

      # Push the Docker image
      - name: Push Docker Image
        run: docker push mohanapriya1808/2048-game:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Set up SSH to EC2
      - name: SSH to EC2 Instance
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            
            sudo apt-get update

            # Install Docker if not already installed
            sudo apt-get install -y docker.io

            # Start Docker service if it's not already running
            sudo systemctl start docker
            sudo systemctl enable docker

            # Pull the latest Docker image from Docker Hub
            docker pull mohanapriya1808/2048-game:latest

            # Stop the existing container if running
            docker stop 2048-game || true
            docker rm 2048-game || true

            # Run the new container
            docker run -d -p 80:3000 --name 2048-game --restart unless-stopped mohanapriya1808/2048-game:latest